version: '3.5'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack-full:latest
    hostname: localstack
    networks:
      - localstack-net
    ports:
      - 4566:4566
      - 8081:${PORT_WEB_UI-8080}
    environment:
      - SERVICES=dynamodb,s3,lambda,sqs,cloudformation,sts,iam,cloudwatch,events,ssm,sam
      - DEBUG=1
      - USE_LIGHT_IMAGE=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

  localstack-s3-ui:
    container_name: localstack-s3-ui
    depends_on: [localstack]
    image: gosuper/localstack-s3-ui
    ports:
      - 9000:9000
    environment:
      - API_REQ_FILE_PATH=/tmp/localstack/data/recorded_api_calls.json # Required
      - PORT=9000 # Defaults to 9000
    volumes:
      - ./data:/tmp/localstack

networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net